apiVersion: v1
kind: ConfigMap
metadata:
  name: default-static-files
  namespace: ve-landing
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Virtual Elephant Home Lab</title>
        <link rel="stylesheet" href="/static/styles.css">
    </head>
    <body>
        <div class="container">
            <h1>Welcome to Virtual Elephant Home Lab</h1>
        </div>
    </body>
    </html>
  styles.css: |
    /* General Reset */
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        background-color: #0A192F;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        text-align: center;
        font-family: Arial, sans-serif;
        flex-direction: column;
    }

    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    h1 {
        color: white;
        font-size: 2.5rem;
        font-weight: bold;
        margin-bottom: 20px;
    }

    img {
        width: 150px;
        height: auto;
        margin-bottom: 20px;
    }

    .graphs {
        margin-top: 20px;
    }

    .graphs h2 {
        color: white;
        font-size: 1.5rem;
        margin-bottom: 15px;
    }

    .graphs img {
        width: 400px;
        height: auto;
        margin: 10px;
        border-radius: 5px;
        border: 1px solid #fff;
    }
