apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ve-landing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: harbor.home.virtualelephant.com/ve-lab/nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app/static
              name: ve-landing-storage
      volumes:
        - name: ve-landing-storage
          persistentVolumeClaim:
            claimName: ve-landing-pvc
